
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
  datasource:
    hikari:
#       mysql 8.x.x 부터 allowPublicKeyRetrieval 설정을 해줘야 한다.
      jdbc-url: jdbc:mysql://localhost:3306/jooqdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true